-- MySQL Script generated by MySQL Workbench
-- sáb 21 nov 2020 10:57:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema netflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema netflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netflix` ;
USE `netflix` ;

-- -----------------------------------------------------
-- Table `netflix`.`dim_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`dim_date` ;

CREATE TABLE IF NOT EXISTS `netflix`.`dim_date` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`dim_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`dim_type` ;

CREATE TABLE IF NOT EXISTS `netflix`.`dim_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`dim_rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`dim_rating` ;

CREATE TABLE IF NOT EXISTS `netflix`.`dim_rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`dim_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`dim_details` ;

CREATE TABLE IF NOT EXISTS `netflix`.`dim_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `id_rating` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Rating_idx` (`id_rating` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_dim_rating`
    FOREIGN KEY (`id_rating`)
    REFERENCES `netflix`.`dim_rating` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`fact_netflix_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`fact_netflix_data` ;

CREATE TABLE IF NOT EXISTS `netflix`.`fact_netflix_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `release_year` INT NOT NULL,
  `id_added_date` INT NOT NULL,
  `id_dim_type` INT NOT NULL,
  `id_dim_details` INT NOT NULL,
  `imdb_rating` DOUBLE NOT NULL,
  `imdb_rating_votes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_AddedDate_idx` (`id_added_date` ASC) VISIBLE,
  INDEX `fk_DimType_idx` (`id_dim_type` ASC) VISIBLE,
  INDEX `fk_DimDetails_idx` (`id_dim_details` ASC) VISIBLE,
  UNIQUE INDEX `idMovie_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_dim_date`
    FOREIGN KEY (`id_added_date`)
    REFERENCES `netflix`.`dim_date` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dim_type`
    FOREIGN KEY (`id_dim_type`)
    REFERENCES `netflix`.`dim_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dim_details`
    FOREIGN KEY (`id_dim_details`)
    REFERENCES `netflix`.`dim_details` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`dim_director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`dim_director` ;

CREATE TABLE IF NOT EXISTS `netflix`.`dim_director` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`dim_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`dim_actor` ;

CREATE TABLE IF NOT EXISTS `netflix`.`dim_actor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`dim_country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`dim_country` ;

CREATE TABLE IF NOT EXISTS `netflix`.`dim_country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`dim_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`dim_category` ;

CREATE TABLE IF NOT EXISTS `netflix`.`dim_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`mid_categories_listed_in`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`mid_categories_listed_in` ;

CREATE TABLE IF NOT EXISTS `netflix`.`mid_categories_listed_in` (
  `id_show` INT NOT NULL,
  `id_category` INT NOT NULL,
  PRIMARY KEY (`id_show`, `id_category`),
  INDEX `fk_Categoria_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_categories_fact_netflix_data`
    FOREIGN KEY (`id_show`)
    REFERENCES `netflix`.`fact_netflix_data` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dim_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `netflix`.`dim_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`mid_countries_filmed_in`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`mid_countries_filmed_in` ;

CREATE TABLE IF NOT EXISTS `netflix`.`mid_countries_filmed_in` (
  `id_show` INT NOT NULL,
  `id_country` INT NOT NULL,
  PRIMARY KEY (`id_show`, `id_country`),
  INDEX `fk_Country_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_countries_fact_netflix_data`
    FOREIGN KEY (`id_show`)
    REFERENCES `netflix`.`fact_netflix_data` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dim_country`
    FOREIGN KEY (`id_country`)
    REFERENCES `netflix`.`dim_country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`mid_directors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`mid_directors` ;

CREATE TABLE IF NOT EXISTS `netflix`.`mid_directors` (
  `id_show` INT NOT NULL,
  `id_director` INT NOT NULL,
  PRIMARY KEY (`id_show`, `id_director`),
  INDEX `fk_Director_idx` (`id_director` ASC) VISIBLE,
  CONSTRAINT `fk_directors_fact_netflix_data`
    FOREIGN KEY (`id_show`)
    REFERENCES `netflix`.`fact_netflix_data` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dim_director`
    FOREIGN KEY (`id_director`)
    REFERENCES `netflix`.`dim_director` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`mid_cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`mid_cast` ;

CREATE TABLE IF NOT EXISTS `netflix`.`mid_cast` (
  `id_show` INT NOT NULL,
  `id_actor` INT NOT NULL,
  INDEX `fk_Cast_idx` (`id_actor` ASC) VISIBLE,
  PRIMARY KEY (`id_show`, `id_actor`),
  CONSTRAINT `fk_cast_fact_netflix_data`
    FOREIGN KEY (`id_show`)
    REFERENCES `netflix`.`fact_netflix_data` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dim_actor`
    FOREIGN KEY (`id_actor`)
    REFERENCES `netflix`.`dim_actor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
