-- MySQL Script generated by MySQL Workbench
-- sáb 07 nov 2020 16:04:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shootings_star
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shootings_star` ;

-- -----------------------------------------------------
-- Schema shootings_star
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shootings_star` ;
USE `shootings_star` ;

-- -----------------------------------------------------
-- Table `shootings_star`.`dim_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_address` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`dim_age`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_age` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_age` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `age` VARCHAR(10) NOT NULL,
  `age_range` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`dim_body_camera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_body_camera` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_body_camera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body_camera` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`dim_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_date` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_date` (
  `id` DATETIME NOT NULL,
  `year` INT NOT NULL,
  `month` INT NOT NULL,
  `day` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`dim_death_cause`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_death_cause` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_death_cause` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manner_of_death` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`dim_gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_gender` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_gender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`dim_mental_illness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_mental_illness` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_mental_illness` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mental_illness` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`dim_race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_race` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_race` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `race` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`dim_risk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`dim_risk` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`dim_risk` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `armed` VARCHAR(45) NOT NULL,
  `flee` VARCHAR(45) NOT NULL,
  `threat_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`facts_fatal_police_shooting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`facts_fatal_police_shooting` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`facts_fatal_police_shooting` (
  `victim_id` INT NOT NULL AUTO_INCREMENT,
  `id_dim_age` INT NOT NULL,
  `id_dim_race` INT NOT NULL,
  `id_dim_gender` INT NOT NULL,
  `id_dim_body_camera` INT NOT NULL,
  `id_dim_address` INT NOT NULL,
  `id_dim_date` DATETIME NOT NULL,
  `id_dim_risk` INT NOT NULL,
  `id_dim_death_cause` INT NOT NULL,
  `id_dim_mental_illness` INT NOT NULL,
  PRIMARY KEY (`victim_id`),
  INDEX `fk_id_dim_age_idx` (`id_dim_age` ASC) VISIBLE,
  INDEX `fk_id_dim_race_idx` (`id_dim_race` ASC) VISIBLE,
  INDEX `fk_id_dim_gender_idx` (`id_dim_gender` ASC) VISIBLE,
  INDEX `fk_body_camera_idx` (`id_dim_body_camera` ASC) VISIBLE,
  INDEX `fk_id_dim_address_idx` (`id_dim_address` ASC) VISIBLE,
  INDEX `fk_id_dim_date_idx` (`id_dim_date` ASC) VISIBLE,
  INDEX `fk_id_dim_risk_idx` (`id_dim_risk` ASC) VISIBLE,
  INDEX `fk_id_dim_death_cause_idx` (`id_dim_death_cause` ASC) VISIBLE,
  INDEX `fk_id_dim_mental_illness_idx` (`id_dim_mental_illness` ASC) VISIBLE,
  CONSTRAINT `fk_id_dim_address`
    FOREIGN KEY (`id_dim_address`)
    REFERENCES `shootings_star`.`dim_address` (`id`),
  CONSTRAINT `fk_id_dim_age`
    FOREIGN KEY (`id_dim_age`)
    REFERENCES `shootings_star`.`dim_age` (`id`),
  CONSTRAINT `fk_id_dim_body_camera`
    FOREIGN KEY (`id_dim_body_camera`)
    REFERENCES `shootings_star`.`dim_body_camera` (`id`),
  CONSTRAINT `fk_id_dim_date`
    FOREIGN KEY (`id_dim_date`)
    REFERENCES `shootings_star`.`dim_date` (`id`),
  CONSTRAINT `fk_id_dim_death_cause`
    FOREIGN KEY (`id_dim_death_cause`)
    REFERENCES `shootings_star`.`dim_death_cause` (`id`),
  CONSTRAINT `fk_id_dim_gender`
    FOREIGN KEY (`id_dim_gender`)
    REFERENCES `shootings_star`.`dim_gender` (`id`),
  CONSTRAINT `fk_id_dim_mental_illness`
    FOREIGN KEY (`id_dim_mental_illness`)
    REFERENCES `shootings_star`.`dim_mental_illness` (`id`),
  CONSTRAINT `fk_id_dim_race`
    FOREIGN KEY (`id_dim_race`)
    REFERENCES `shootings_star`.`dim_race` (`id`),
  CONSTRAINT `fk_id_dim_risk`
    FOREIGN KEY (`id_dim_risk`)
    REFERENCES `shootings_star`.`dim_risk` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings_star`.`temp_dataset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings_star`.`temp_dataset` ;

CREATE TABLE IF NOT EXISTS `shootings_star`.`temp_dataset` (
  `id` INT NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `manner_of_death` TEXT NULL DEFAULT NULL,
  `armed` TEXT NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `gender` TEXT NULL DEFAULT NULL,
  `race` TEXT NULL DEFAULT NULL,
  `city` TEXT NULL DEFAULT NULL,
  `state` TEXT NULL DEFAULT NULL,
  `signs_of_mental_illness` TEXT NULL DEFAULT NULL,
  `threat_level` TEXT NULL DEFAULT NULL,
  `flee` TEXT NULL DEFAULT NULL,
  `body_camera` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
