-- MySQL Script generated by MySQL Workbench
-- sáb 24 out 2020 15:46:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema covid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema covid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `covid` ;
USE `covid` ;

-- -----------------------------------------------------
-- Table `covid`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `covid`.`country` ;

CREATE TABLE IF NOT EXISTS `covid`.`country` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `population` INT NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`dayStats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `covid`.`dayStats` ;

CREATE TABLE IF NOT EXISTS `covid`.`dayStats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` DATE NOT NULL,
  `countryId` VARCHAR(45) NOT NULL,
  `weekNr` INT NOT NULL,
  `#cases` INT NULL DEFAULT 0,
  `#deaths` INT NULL DEFAULT 0,
  `#cumulativePer100` BIGINT NULL DEFAULT 0,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  INDEX `id_idx` (`countryId` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_dayStats_country`
    FOREIGN KEY (`countryId`)
    REFERENCES `covid`.`country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`weekStats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `covid`.`weekStats` ;

CREATE TABLE IF NOT EXISTS `covid`.`weekStats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `weekNr` INT NOT NULL,
  `countryId` VARCHAR(45) NOT NULL,
  `#newCases` INT NULL DEFAULT 0,
  `#testsDone` INT NULL DEFAULT 0,
  `testingRate` FLOAT NULL DEFAULT 0,
  `positivityRate` FLOAT NULL DEFAULT 0,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  INDEX `fk_weekStats_country_idx` (`countryId` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_weekStats_country`
    FOREIGN KEY (`countryId`)
    REFERENCES `covid`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `covid` ;

-- -----------------------------------------------------
-- procedure softDeleteEntry
-- -----------------------------------------------------

USE `covid`;
DROP procedure IF EXISTS `covid`.`softDeleteEntry`;

DELIMITER $$
USE `covid`$$
create procedure softDeleteEntry (
   tableName varchar(64),
   id varchar(64)
) 
begin
	set @tableName = tableName;
    set @id = id;
	set @sqlText = concat('update ',@tableName,' set status=\'deleted\' where id=\'',@id,'\'');

	prepare stmt from @sqlText;
	execute stmt;
	deallocate prepare stmt;
end$$

DELIMITER ;
USE `covid`;

DELIMITER $$

USE `covid`$$
DROP TRIGGER IF EXISTS `covid`.`dayStats_init_created_at` $$
USE `covid`$$
CREATE DEFINER = CURRENT_USER TRIGGER `covid`.`dayStats_init_created_at` BEFORE INSERT ON `dayStats` FOR EACH ROW
BEGIN
	SET NEW.createdAt = now();
END$$


USE `covid`$$
DROP TRIGGER IF EXISTS `covid`.`weekStats_init_created_at` $$
USE `covid`$$
CREATE DEFINER = CURRENT_USER TRIGGER `covid`.`weekStats_init_created_at` BEFORE INSERT ON `weekStats` FOR EACH ROW
BEGIN
	SET NEW.createdAt = now();
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
