INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('AK','Alaska',626933);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('AL','Alabama',4447207);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('AR','Arkansas',2673293);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('AZ','Arizona',5130247);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('CA','California',33871653);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('CO','Colorado',4302086);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('CT','Connecticut',3405650);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('DC','District of Columbia',572086);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('DE','Delaware',783559);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('FL','Florida',15982571);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('GA','Georgia',8186653);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('HI','Hawaii',1211497);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('IA','Iowa',2926538);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('ID','Idaho',1293957);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('IL','Illinois',12419927);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('IN','Indiana',6080827);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('KS','Kansas',2688925);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('KY','Kentucky',4042193);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('LA','Louisiana',4469035);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('MA','Massachusetts',8046346);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('MD','Maryland',18977026);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('ME','Maine',1274779);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('MI','Michigan',642237);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('MN','Minnesota',11353336);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('MO','Missouri',3421524);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('MS','Mississippi',3450451);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('MT','Montana',5296647);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('NC','North Carolina',1711230);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('ND','North Dakota',1998250);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('NE','Nebraska',6349364);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('NH','New Hampshire',4919631);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('NJ','New Jersey',2844754);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('NM','New Mexico',5596564);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('NV','Nevada',9938823);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('NY','New York',902200);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('OH','Ohio',1235807);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('OK','Oklahoma',8414764);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('OR','Oregon',1819017);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('PA','Pennsylvania',12280548);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('RI','Rhode Island',1048259);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('SC','South Carolina',4012023);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('SD','South Dakota',754858);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('TN','Tennessee',5689427);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('TX','Texas',20851028);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('UT','Utah',2233183);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('VA','Virginia',7079057);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('VT','Vermont',608613);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('WA','Washington',5894281);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('WI','Wisconsin',5363757);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('WV','West Virginia',1808193);
INSERT INTO `dim_state` (`id`,`name`,`population`) VALUES ('WY','Wyoming',493786);
