-- MySQL Script generated by MySQL Workbench
-- sáb 07 nov 2020 14:02:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shootings
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shootings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shootings` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `shootings` ;

-- -----------------------------------------------------
-- Table `shootings`.`dim_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings`.`dim_address` ;

CREATE TABLE IF NOT EXISTS `shootings`.`dim_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4096
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings`.`dim_age`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings`.`dim_age` ;

CREATE TABLE IF NOT EXISTS `shootings`.`dim_age` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `age` VARCHAR(10) NOT NULL,
  `age_range` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings`.`dim_body_camera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings`.`dim_body_camera` ;

CREATE TABLE IF NOT EXISTS `shootings`.`dim_body_camera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body_camera` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings`.`dim_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings`.`dim_date` ;

CREATE TABLE IF NOT EXISTS `shootings`.`dim_date` (
  `id` DATETIME NOT NULL,
  `year` INT NOT NULL,
  `month` INT NOT NULL,
  `day` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings`.`dim_gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings`.`dim_gender` ;

CREATE TABLE IF NOT EXISTS `shootings`.`dim_gender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings`.`dim_race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings`.`dim_race` ;

CREATE TABLE IF NOT EXISTS `shootings`.`dim_race` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `race` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shootings`.`facts_fatal_police_shooting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shootings`.`facts_fatal_police_shooting` ;

CREATE TABLE IF NOT EXISTS `shootings`.`facts_fatal_police_shooting` (
  `victim_id` INT NOT NULL AUTO_INCREMENT,
  `id_dim_age` INT NULL,
  `id_dim_race` INT NULL,
  `id_dim_gender` INT NULL,
  `id_dim_body_camera` INT NULL,
  `id_dim_address` INT NULL,
  `id_dim_date` DATETIME NULL,
  PRIMARY KEY (`victim_id`),
  INDEX `fk_id_dim_age_idx` (`id_dim_age` ASC) VISIBLE,
  INDEX `fk_id_dim_race_idx` (`id_dim_race` ASC) VISIBLE,
  INDEX `fk_id_dim_gender_idx` (`id_dim_gender` ASC) VISIBLE,
  INDEX `fk_body_camera_idx` (`id_dim_body_camera` ASC) VISIBLE,
  INDEX `fk_id_dim_address_idx` (`id_dim_address` ASC) VISIBLE,
  INDEX `fk_id_dim_date_idx` (`id_dim_date` ASC) VISIBLE,
  CONSTRAINT `fk_id_dim_age`
    FOREIGN KEY (`id_dim_age`)
    REFERENCES `shootings`.`dim_age` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_dim_race`
    FOREIGN KEY (`id_dim_race`)
    REFERENCES `shootings`.`dim_race` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_dim_gender`
    FOREIGN KEY (`id_dim_gender`)
    REFERENCES `shootings`.`dim_gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_dim_body_camera`
    FOREIGN KEY (`id_dim_body_camera`)
    REFERENCES `shootings`.`dim_body_camera` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_dim_address`
    FOREIGN KEY (`id_dim_address`)
    REFERENCES `shootings`.`dim_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_dim_date`
    FOREIGN KEY (`id_dim_date`)
    REFERENCES `shootings`.`dim_date` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
